lista = ['Ana', 'Lia', 'Rui', 'Paulo', 'Dani']
print(lista[1:3]) # print ['Lia', 'Rui']
print(lista[1:-1]) # print ['Lia', 'Rui', 'Paulo']
print(lista[1:]) # print ['Lia', 'Rui', 'Paulo', 'Dani']
print(lista[:-1]) # print ['Ana', 'Lia', 'Rui', 'Paulo']
print(lista[:]) # print a lista inteira ['Ana', 'Lia', 'Rui', 'Paulo', 'Dani']
print(lista[::2]) # print a lista pulando de 2 em 2 ['Ana', 'Rui', 'Dani']
print(lista[::-1]) # inverte a lista ['Dani', 'Paulo', 'Rui', 'Lia', 'Ana']
del lista[2]
print(lista) # delete o indice 2 da lista, no caso deletou o 'Rui', ['Ana', 'Lia', 'Paulo', 'Dani']
del lista[1:]
print(lista) # delete do indice 1 em diante, no caso deletou todos menos a Ana, ['Ana']
